-- MySQL Script generated by MySQL Workbench
-- 07/22/14 21:20:06
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema accesspoint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accesspoint` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `accesspoint` ;

-- -----------------------------------------------------
-- Table `accesspoint`.`Vertices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesspoint`.`Vertices` (
  `idVertex` INT NOT NULL AUTO_INCREMENT,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  PRIMARY KEY (`idVertex`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesspoint`.`Mac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesspoint`.`Mac` (
  `idMac` INT NOT NULL AUTO_INCREMENT,
  `macAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesspoint`.`DirectionTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesspoint`.`DirectionTime` (
  `idDirectionTime` INT NOT NULL AUTO_INCREMENT,
  `direction` CHAR NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idDirectionTime`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesspoint`.`Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesspoint`.`Data` (
  `idData` INT NOT NULL AUTO_INCREMENT,
  `idVertex` INT NOT NULL,
  `idMac` INT NOT NULL,
  `strength` INT NOT NULL,
  `idDirectionTime` INT NOT NULL,
  PRIMARY KEY (`idData`),
  CONSTRAINT `idVertex`
    FOREIGN KEY (`idVertex`)
    REFERENCES `accesspoint`.`Vertices` (`idVertex`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idMac`
    FOREIGN KEY (`idMac`)
    REFERENCES `accesspoint`.`Mac` (`idMac`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idDirectionTime`
    FOREIGN KEY (`idDirectionTime`)
    REFERENCES `accesspoint`.`DirectionTime` (`idDirectionTime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
